FROM registry.vanillaos.org/vanillaos/core:main
LABEL maintainer="Vanilla OS Contributors"

# Copy bucket in /tmp
COPY bucket /tmp/bucket

# Update index
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get clean

# Set default PATH
RUN echo 'PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"' > /etc/environment
RUN sed -i '4,10d' /etc/profile

# Following code is generated by prepare.sh, do not edit manually
# --- BEGIN GENERATED CODE ---
@@PKGS_INST@@
# --- END GENERATED CODE ---