name: Vanilla Desktop
id: desktop

stages:
- id: build
  base: ghcr.io/vanilla-os/core:main
  singlelayer: false
  labels:
    maintainer: Vanilla OS Contributors
  args:
    DEBIAN_FRONTEND: noninteractive
  runs:
    commands:
      - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

  modules:
  - name: init-setup
    type: shell
    commands:
    - echo 'PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"' > /etc/environment
    - sed -i '4,10d' /etc/profile
    - apt update
    - apt upgrade -y
    - apt clean
    - apt-mark hold snapd gnome-software-plugin-snap
    - apt -y install squashfs-tools minisign

  - name: vanilla-tools
    type: shell
    source:
      type: tar
      # switch to production build once in production
      url: https://github.com/Vanilla-OS/vanilla-tools/releases/download/continuous/vanilla-tools.tar.gz
    commands:
    - mkdir -p /usr/bin
    - cp /sources/vanilla-tools/vanilla-tools/lpkg /usr/bin/lpkg
    - cp /sources/vanilla-tools/vanilla-tools/cur-gpu /usr/bin/cur-gpu
    - chmod +x /usr/bin/lpkg
    - chmod +x /usr/bin/cur-gpu

  - name: packages-modules
    type: includes
    includes:
      - modules/00-vanilla-desktop-base.yml
      - modules/00-vanilla-backgrounds.yml
      - modules/00-vanilla-first-setup.yml
      - modules/00-vanilla-gnome-default-settings.yml
      - modules/00-vanilla-system-operator.yml
      - modules/00-vanilla-apx-gui.yml
      - modules/00-vanilla-tour.yml
      - modules/00-vanilla-sideload.yml
      - modules/00-vanilla-updates-utility.yml
      - modules/02-waydroid-modules.yml
      - modules/03-fswarn.yml
      - modules/10-vanilla-abroot-rollback-notifier.yml
      - modules/20-gnome-core.yml
      - modules/21-gnome-control-center.yml
      - modules/30-gnome-essentials.yml
      - modules/40-gnome-appearance.yml
      - modules/50-laptop-goodies.yml
      - modules/60-media.yml
      - modules/80-printers.yml
      - modules/90-3d-utils.yml
      - modules/100-accessibility.yml
      - modules/110-fonts.yml
      - modules/120-network.yml
      - modules/121-disable-ssh-daemon.yml
      - modules/130-plymouth.yml
      - modules/131-plymouth-theme-vanilla.yml
      - modules/140-password.yml
      - modules/160-utilities.yml
      - modules/170-gnome-software-vso-plugin.yml
      - modules/200-gnome-common.yml
      - modules/210-libs-extra.yml
      - modules/211-abroot-fstab-mount.yml
      - modules/998-vanilla-cleanup.yml
      - modules/999-pkg-cleanup.yml
      - modules/999-clear-first-setup-steps-unit.yml

  - name: firstsetup-default-session
    type: shell
    commands:
    - sed 's/Session=/Session=firstsetup/g' -i /usr/share/accountsservice/user-templates/administrator
    - sed 's/Session=/Session=firstsetup/g' -i /usr/share/accountsservice/user-templates/standard

  - name: apx-vso-pico-shutdown-service
    type: shell
    commands:
    - mkdir -p /etc/systemd/user/graphical-session.target.wants/
    - ln -s /etc/systemd/user/apx-vso-pico.service /etc/systemd/user/graphical-session.target.wants/

  - name: gnome-software-setup
    type: shell
    commands:
    - rm /usr/lib/*/gnome-software/plugins-20/libgs_plugin_packagekit.so

  - name: cleanup
    type: shell
    commands:
    - apt autoremove -y
    - apt clean
    - lpkg --lock

  - name: sysconf-setup
    type: shell
    commands:
      - rsync -a /etc/ /sysconf/

  - name: fsguard
    type: fsguard
    CustomFsGuard: false
    FsGuardLocation: "/usr/sbin/FsGuard"
    GenerateKey: true
    FilelistPaths: ["/usr/bin"]
    modules:
      - name: remove-prev-fsguard
        type: shell
        commands:
          - rm -rf /FsGuard
          - rm -f ./minisign.pub ./minisign.key
          - chmod +x /usr/share/init.d/010-fsguard.sh

  - name: cleanup2
    type: shell
    commands:
      - rm -rf /tmp/*
      - rm -rf /var/tmp/*
      - rm -rf /sources
